<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../FlipSwitcher/Services/WindowActivationService.cs" Link="Services/WindowActivationService.cs" />
  </ItemGroup>
</Project>
